project_id = "agpeebvrrcytghmilzss"

[functions.send-invite-email]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.generate-monthly-report]
verify_jwt = true

[functions.generate-recurring-transactions]
verify_jwt = true

[functions.generate-contract-transactions]
verify_jwt = true

[functions.onboarding]
verify_jwt = true

[functions.create-company-admin]
verify_jwt = true

[functions.super-admin-users]
verify_jwt = true

[functions.reset-company-data]
verify_jwt = true

[functions.analyze-report]
verify_jwt = true

[functions.analyze-bank-statement]
verify_jwt = true

[functions.parse-transactions-text]
verify_jwt = true

[functions.parse-contracts-text]
verify_jwt = true
